In [187]:
from pathlib import Path
import numpy as np

def load_path(path):
    res = []
    with Path(path).open() as f:
        for line in f.readlines():
            pos, vel = line.strip().split("@")
            pos = np.array([int(v) for v in pos.strip().split(", ")])
            vel = np.array([int(v) for v in vel.strip().split(", ")])
            res.append((pos, vel))
    return res

In [188]:
hail = load_path("24_test.txt")
hail

[(array([19, 13, 30]), array([-2,  1, -2])),
 (array([18, 19, 22]), array([-1, -1, -2])),
 (array([20, 25, 34]), array([-2, -2, -4])),
 (array([12, 31, 28]), array([-1, -2, -1])),
 (array([20, 19, 15]), array([ 1, -5, -3]))]

In [189]:
import matplotlib.pyplot as pl

def check(h1, h2, l, r):
    (p1_x, p1_y), (v1_x, v1_y) = h1[0][:2], h1[1][:2]
    (p2_x, p2_y), (v2_x, v2_y) = h2[0][:2], h2[1][:2]
    
    d = ((v2_x * v1_y) -  (v2_y * v1_x))
    if d == 0:
        return False
    b = (v1_y * p1_x - v1_y * p2_x - v1_x * p1_y + v1_x * p2_y) / d
    
    if b < 0:
        return False
    x = p2_x + b * v2_x
    a = (x - p1_x) / v1_x
    if a < 0:
        return False
    
    y = p2_y + b * v2_y
    return l <= x <= r and l <= y <= r

def intersect(hails, l, r):
    n = len(hails)
    res = 0
    for i in range(n):
        for j in range(i+1, n):
            if check(hails[i], hails[j], l, r):
                res += 1
    return res

In [190]:
hail = load_path("24_test.txt")
intersect(hail, 7, 27)

2

In [191]:
hail = load_path("24_input.txt")
intersect(hail, 200000000000000, 400000000000000)  # 12938

12938

In [192]:
from sympy.solvers import solve
from sympy import Symbol

def resolve(hails):
    a = Symbol('a')
    b = Symbol('b')
    c = Symbol('c')
    d = Symbol('d')
    X = Symbol('X')
    Y = Symbol('Y')
    Z = Symbol('Z')
    A = Symbol('A')
    B = Symbol('B')
    C = Symbol('C')
    (p1_x, p1_y, p1_z), (v1_x, v1_y, v1_z) = hail[0]
    (p2_x, p2_y, p2_z), (v2_x, v2_y, v2_z) = hail[1]
    (p3_x, p3_y, p3_z), (v3_x, v3_y, v3_z) = hail[2]
    (p4_x, p4_y, p4_z), (v4_x, v4_y, v4_z) = hail[3]
    res = solve([a*v1_x + p1_x - a*X - A,
       a*v1_y + p1_y - a*Y - B,
       a*v1_z + p1_z - a*Z - C,
       b*v2_x + p2_x - b*X - A,
       b*v2_y + p2_y - b*Y - B,
       b*v2_z + p2_z - b*Z - C,
       c*v3_x + p3_x - c*X - A,
       c*v3_y + p3_y - c*Y - B,
       c*v3_z + p3_z - c*Z - C,
       d*v4_x + p4_x - d*X - A,
       d*v4_y + p4_y - d*Y - B,
       d*v4_z + p4_z - d*Z - C,])[0]
    return sum([res[A], res[B], res[C]])

In [193]:
hail = load_path("24_test.txt")
resolve(hail) == 47

True

In [194]:
hail = load_path("24_input.txt")
print(resolve(hail))  # 976976197397181

976976197397181
